# Dataframe and Series

- dataframe is 2D, in rows and columns
- series is 1D labelled array. for individual row or column representation of a dataframe
- uses Boolean masking for each dataframe column series. it is a filtering technique ​that overlays a Boolean grid onto a dataframe ​in order to select only the values in the dataframe ​that align with the True values

In [3]:
import pandas as pd

clothes = pd.DataFrame({'type': ['pants', 'shirt', 'shirt', 'pants', 'shirt', 'pants'],
                       'color': ['red', 'blue', 'green', 'blue', 'green', 'red'],
                       'price_usd': [20, 35, 50, 40, 100, 75],
                       'mass_g': [125, 440, 680, 200, 395, 485]})


clothes

    type  color  price_usd  mass_g
0  pants    red         20     125
1  shirt   blue         35     440
2  shirt  green         50     680
3  pants   blue         40     200
4  shirt  green        100     395
5  pants    red         75     485

In [4]:

clothes.groupby(['type', 'color']).size()

type   color
pants  blue     1
       red      2
shirt  blue     1
       green    2
dtype: int64

In [7]:

clothes.groupby('color').agg({'price_usd': ['mean', 'max'],
                             'mass_g': ['mean', 'min']})

      price_usd      mass_g
           mean  max   mean  min
color
blue       37.5   40  320.0  200
green      75.0  100  537.5  395
red        47.5   75  305.0  125

In [6]:
grouped = clothes.groupby(['color', 'type']).agg(['mean', 'min'])
grouped

            price_usd     mass_g
                 mean min   mean  min
color type
blue  pants      40.0  40  200.0  200
      shirt      35.0  35  440.0  440
green shirt      75.0  50  537.5  395
red   pants      47.5  20  305.0  125

In [8]:

print(grouped.index)

print(grouped.columns)

MultiIndex([( 'blue', 'pants'),
            ( 'blue', 'shirt'),
            ('green', 'shirt'),
            (  'red', 'pants')],
           names=['color', 'type'])
MultiIndex([('price_usd', 'mean'),
            ('price_usd',  'min'),
            (   'mass_g', 'mean'),
            (   'mass_g',  'min')],
           )

In [9]:
grouped.loc[:, ('price_usd', 'min')]

color  type
blue   pants    40
       shirt    35
green  shirt    50
red    pants    20
Name: (price_usd, min), dtype: int64

In [10]:

grouped.loc['blue', :]

      price_usd     mass_g
           mean min   mean  min
type
pants      40.0  40  200.0  200
shirt      35.0  35  440.0  440

In [11]:

grouped.loc[('green', 'shirt'), :]

price_usd  mean     75.0
           min      50.0
mass_g     mean    537.5
           min     395.0
Name: (green, shirt), dtype: float64

In [12]:
clothes.groupby(['color', 'type'], as_index=False).mean()

   color   type  price_usd  mass_g
0   blue  pants       40.0   200.0
1   blue  shirt       35.0   440.0
2  green  shirt       75.0   537.5
3    red  pants       47.5   305.0