# Data Structure

- For python, it is collection of data values or objects that contain different data types
- Mutability:  ​Mutability refers to the ability to change ​the internal state of a data structure
- Immutability: Not mutable
- ​Data structures also enable more efficient storage, ​access, and modifications. 
- Note that string is a data type, not data structure
- for string manipulation, we are over-writing the variable instead of changing the string. this is string's immutability
- Python data structures:
    - lists
    - tuple (immutable sequence, can contain elements of any data type.)

# Dataframe operation examples

In [1]:
import numpy as np
import pandas as pd

# Instantiate a dictionary of planetary data.
data = {'planet': ['Mercury', 'Venus', 'Earth', 'Mars'],
        'radius_km': [2440, 6052, 6371, 3390],
        'moons': [0, 0, 1, 2],
        }
# Use pd.DataFrame() function to convert dictionary to dataframe.
df1 = pd.DataFrame(data)

# Instantiate a dictionary of planetary data.
data = {'planet': ['Jupiter', 'Saturn', 'Uranus', 'Neptune'],
        'radius_km': [69911, 58232, 25362, 24622],
        'moons': [80, 83, 27, 14],
        }
# Use pd.DataFrame() function to convert dictionary to dataframe.
df2 = pd.DataFrame(data)

# The pd.concat() function can combine the two dataframes along axis 0,
# with the second dataframe being added as new rows to the first dataframe.
df3 = pd.concat([df1, df2], axis=0)
df3

    planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
0  Jupiter      69911     80
1   Saturn      58232     83
2   Uranus      25362     27
3  Neptune      24622     14

In [2]:
# Reset the row indices.
df3 = df3.reset_index(drop=True)
df3

    planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
4  Jupiter      69911     80
5   Saturn      58232     83
6   Uranus      25362     27
7  Neptune      24622     14

In [3]:
import numpy as np
import pandas as pd

# Instantiate a dictionary of planetary data.
data = {'planet': ['Mercury', 'Venus', 'Earth', 'Mars',
                   'Jupiter', 'Saturn', 'Uranus', 'Neptune'],
        'radius_km': [2440, 6052, 6371, 3390, 69911, 58232,
                     25362, 24622],
        'moons': [0, 0, 1, 2, 80, 83, 27, 14],
        'type': ['terrestrial', 'terrestrial', 'terrestrial', 'terrestrial',
                 'gas giant', 'gas giant', 'ice giant', 'ice giant'],
        'rings': ['no', 'no', 'no', 'no', 'yes', 'yes', 'yes','yes'],
        'mean_temp_c': [167, 464, 15, -65, -110, -140, -195, -200],
        'magnetic_field': ['yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'yes']
        }

# Use pd.DataFrame() function to convert dictionary to dataframe.
planets = pd.DataFrame(data)
planets

    planet  radius_km  moons         type rings  mean_temp_c magnetic_field
0  Mercury       2440      0  terrestrial    no          167            yes
1    Venus       6052      0  terrestrial    no          464             no
2    Earth       6371      1  terrestrial    no           15            yes
3     Mars       3390      2  terrestrial    no          -65             no
4  Jupiter      69911     80    gas giant   yes         -110            yes
5   Saturn      58232     83    gas giant   yes         -140            yes
6   Uranus      25362     27    ice giant   yes         -195            yes
7  Neptune      24622     14    ice giant   yes         -200            yes

In [8]:
planets.groupby(['type', 'magnetic_field']).sum()

                                   planet  radius_km  moons   rings  \
type        magnetic_field
gas giant   yes             JupiterSaturn     128143    163  yesyes
ice giant   yes             UranusNeptune      49984     41  yesyes
terrestrial no                  VenusMars       9442      2    nono
            yes              MercuryEarth       8811      1    nono

                            mean_temp_c
type        magnetic_field
gas giant   yes                    -250
ice giant   yes                    -395
terrestrial no                      399
            yes                     182

In [15]:
# Define a function that returns the 90 percentile of an array.
def percentile_90(x):
    return x.quantile(0.9)

# Group by type and magnetic_field, then use the agg() function to apply the
# mean and the custom-defined `percentile_90()` function to the numeric
# columns for each group.
planets.groupby(['moons', 'mean_temp_c'])[['radius_km',	'moons'	,	'mean_temp_c']].agg(['mean', percentile_90])

                  radius_km               moons               mean_temp_c  \
                       mean percentile_90  mean percentile_90        mean
moons mean_temp_c
0      167           2440.0        2440.0   0.0           0.0       167.0
       464           6052.0        6052.0   0.0           0.0       464.0
1      15            6371.0        6371.0   1.0           1.0        15.0
2     -65            3390.0        3390.0   2.0           2.0       -65.0
14    -200          24622.0       24622.0  14.0          14.0      -200.0
27    -195          25362.0       25362.0  27.0          27.0      -195.0
80    -110          69911.0       69911.0  80.0          80.0      -110.0
83    -140          58232.0       58232.0  83.0          83.0      -140.0


                  percentile_90
moons mean_temp_c
0      167                167.0
       464                464.0
1      15                  15.0
2     -65                 -65.0
14    -200               -200.0
27    -195               -195.0
80    -110               -110.0
83    -140               -140.0

In [16]:
my_list = ['Macduff', 'Malcolm', 'Macbeth', 'Banquo']
my_list[1:3] = [1, 2, 3, 4]
print(my_list)

['Macduff', 1, 2, 3, 4, 'Banquo']

# Tuple

- When using parentheses to declare a tuple with just a single element, you must use a trailing comma. 
- No parentheses, but each element followed by a comma (even if there’s only one element):

In [17]:
test1 = (1)
test2 = (2,)

print(type(test1))
print(type(test2))

<class 'int'>
<class 'tuple'>

In [18]:
tuple1 = 1,
tuple2 = 2, 3

print(type(tuple1))
print(type(tuple2))

<class 'tuple'>
<class 'tuple'>

In [19]:
cities = ['Paris', 'Lagos', 'Mumbai']
countries = ['France', 'Nigeria', 'India']
places = zip(cities, countries)


print(places)
print(list(places))

<zip object at 0x0000024EE6100D00>
[('Paris', 'France'), ('Lagos', 'Nigeria'), ('Mumbai', 'India')]

In [20]:
scientists = [('Nikola', 'Tesla'), ('Charles', 'Darwin'), ('Marie', 'Curie')]
given_names, surnames = zip(*scientists)
print(given_names)
print(surnames)

('Nikola', 'Charles', 'Marie')
('Tesla', 'Darwin', 'Curie')